version: '3.8'

services:
  postgres_db:
    image: postgres:16
    container_name: practice_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  fastapi:
    build:
      context: ./backend/fastapi
      dockerfile: Dockerfile
    container_name: fastapi_practice
    ports:
      - "8000:8000"
    volumes:
      - ./backend/fastapi:/app
    depends_on:
      - postgres_db
    networks:
      - app_network
    environment:
      - ai_bot_db_user=postgres
      - ai_bot_db_password=postgres
      - ai_bot_db_name=ai_bot_db
      - ai_bot_db_host=postgres_db
      - ai_bot_cloud_sql_connection_name=local
      - environment=development
      # Supabase configuration (optional)
      - supabase_url=${SUPABASE_URL:-}
      - supabase_key=${SUPABASE_KEY:-}
      - supabase_service_role_key=${SUPABASE_SERVICE_ROLE_KEY:-}
      - use_supabase=${USE_SUPABASE:-false}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    environment:
      - NEXT_PUBLIC_API_URL=http://fastapi:8000
      # Supabase configuration (optional)
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_KEY:-}
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge 
