version: '3.8'

services:
  postgres_db:
    image: postgres:16
    container_name: practice_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ai_bot_db}
    # Internal communication only - no need to expose port to host
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  fastapi:
    build:
      context: ./backend/fastapi
      dockerfile: Dockerfile
    container_name: fastapi_practice
    restart: unless-stopped
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    volumes:
      - ./backend/fastapi:/app
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - AI_BOT_DB_USER=${AI_BOT_DB_USER:-postgres}
      - AI_BOT_DB_PASSWORD=${AI_BOT_DB_PASSWORD:-postgres}
      - AI_BOT_DB_NAME=${AI_BOT_DB_NAME:-ai_bot_db}
      - AI_BOT_DB_HOST=${AI_BOT_DB_HOST:-postgres_db}
      - AI_BOT_CLOUD_SQL_CONNECTION_NAME=${AI_BOT_CLOUD_SQL_CONNECTION_NAME:-local}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      fastapi:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://fastapi:8000}
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge 
