name: Auto Label on Analysis Complete (Simple with Logs)
on:
  issue_comment:
    types: [created]

jobs:
  add-label:
    # Claude[bot]のコメントで、ANALYSIS_COMPLETEが含まれる場合のみ
    if: |
      github.event.comment.user.login == 'claude[bot]' &&
      contains(github.event.comment.body, '[ANALYSIS_COMPLETE]')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Log Comment Info
        run: |
          echo "========================================"
          echo "CLAUDE ANALYSIS COMPLETE DETECTED"
          echo "========================================"
          echo "Time: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Issue #: ${{ github.event.issue.number }}"
          echo "Comment ID: ${{ github.event.comment.id }}"
          echo "User: ${{ github.event.comment.user.login }}"
          echo "User Type: ${{ github.event.comment.user.type }}"
          echo "----------------------------------------"
          echo "COMMENT PREVIEW (first 200 chars):"
          echo "${COMMENT_BODY:0:200}..."
          echo "----------------------------------------"
          echo "COMMENT END (last 200 chars):"
          echo "...${COMMENT_BODY: -200}"
          echo "========================================"
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}

      - name: Add Label
        uses: actions/github-script@v7
        with:
          script: |
            console.log('=== ADDING LABEL TO ISSUE ===');
            console.log('Repository:', context.repo.owner + '/' + context.repo.repo);
            console.log('Issue Number:', context.issue.number);
            console.log('Label to add:', 'workflow:ready-for-impl');
            
            try {
              const result = await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['workflow:ready-for-impl']
              });
              
              console.log('✅ Label added successfully!');
              console.log('Response status:', result.status);
              console.log('Current labels on issue:', result.data.map(l => l.name).join(', '));
              
            } catch (error) {
              console.error('❌ Failed to add label!');
              console.error('Error message:', error.message);
              console.error('Error status:', error.status);
              console.error('Full error:', JSON.stringify(error, null, 2));
              throw error;
            }

  # デバッグ用: 全てのClaudeコメントをログ（条件を満たさない場合も）
  debug-all-claude-comments:
    if: github.event.comment.user.login == 'claude[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Log All Claude Comments
        run: |
          echo "========================================"
          echo "CLAUDE COMMENT (Debug)"
          echo "========================================"
          echo "Has ANALYSIS_COMPLETE: ${{ contains(github.event.comment.body, '[ANALYSIS_COMPLETE]') }}"
          echo "Comment length: ${#COMMENT_BODY}"
          echo "First 100 chars: ${COMMENT_BODY:0:100}"
          if [[ "${{ contains(github.event.comment.body, '[ANALYSIS_COMPLETE]') }}" == "false" ]]; then
            echo "❌ This Claude comment does NOT contain [ANALYSIS_COMPLETE]"
          else
            echo "✅ This Claude comment CONTAINS [ANALYSIS_COMPLETE]"
          fi
          echo "========================================"
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
