name: Auto Create PR for Claude Bot

on:
  push:
    branches:
      - 'claude/issue-*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug Info
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          
      - name: Check if Claude Bot
        run: |
          if [[ "${{ github.actor }}" == *"claude"* ]]; then
            echo "This is Claude bot"
          else
            echo "This is NOT Claude bot, it's: ${{ github.actor }}"
          fi
          
      - name: Extract Issue Number
        id: extract
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          ISSUE=$(echo $BRANCH | grep -oP 'issue-\K\d+')
          echo "issue_number=$ISSUE" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
          echo "Extracted: Issue=$ISSUE, Branch=$BRANCH"
      
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 既存のPRをチェック
          EXISTING_PR=$(gh pr list \
            --repo ${{ github.repository }} \
            --head "${{ steps.extract.outputs.branch_name }}" \
            --json number \
            --jq length)
          
          if [ "$EXISTING_PR" -eq 0 ]; then
            gh pr create \
              --repo ${{ github.repository }} \
              --title "Implementation: Issue #${{ steps.extract.outputs.issue_number }}" \
              --body "Closes #${{ steps.extract.outputs.issue_number }}\n\nImplemented by Claude bot" \
              --base main \
              --head ${{ steps.extract.outputs.branch_name }}
          else
            echo "PR already exists for this branch"
          fi
