name: Auto Create PR for Claude Bot

on:
  push:
    branches:
      - 'claude/issue-*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'claude[bot]'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract Issue Number
        id: extract
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          ISSUE=$(echo $BRANCH | grep -oP 'issue-\K\d+')
          echo "issue_number=$ISSUE" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
      
      - name: Get Issue Details
        id: issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.extract.outputs.issue_number }}
            });
            return issue.data;
      
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Implementation: ${{ fromJson(steps.issue.outputs.result).title }}" \
            --body "Closes #${{ steps.extract.outputs.issue_number }}\n\nImplemented by Claude bot\n\n${{ fromJson(steps.issue.outputs.result).body }}" \
            --label "workflow:ready-for-review" \
            --base main \
            --head ${{ steps.extract.outputs.branch_name }}
