name: Auto Create PR for Claude Bot

on:
  push:
    branches:
      - 'claude/issue-*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'claude[bot]'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract Issue Number
        id: extract
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          ISSUE=$(echo $BRANCH | grep -oP 'issue-\K\d+')
          echo "issue_number=$ISSUE" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
      
      - name: Setup Labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = ['workflow:ready-for-review'];
            for (const label of labels) {
              try {
                await github.rest.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label
                });
              } catch (error) {
                if (error.status === 404) {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label,
                    color: '0e8a16'
                  });
                }
              }
            }
      
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # PRを作成（ラベルエラーは後で処理）
          PR_URL=$(gh pr create \
            --title "Implementation: Issue #${{ steps.extract.outputs.issue_number }}" \
            --body "Closes #${{ steps.extract.outputs.issue_number }}\n\nImplemented by Claude bot" \
            --base main \
            --head ${{ steps.extract.outputs.branch_name }} \
            --label "workflow:ready-for-review" 2>&1 | grep -o 'https://.*' || true)
          
          echo "PR created: $PR_URL"
