name: Auto Create PR for Claude Bot

on:
  push:
    branches:
      - 'claude/issue-*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'claude[bot]'
    
    steps:
      - name: Extract Issue Number
        id: extract
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          ISSUE=$(echo $BRANCH | grep -oP 'issue-\K\d+')
          echo "issue_number=$ISSUE" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
      
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --repo ${{ github.repository }} \
            --title "Implementation: Issue #${{ steps.extract.outputs.issue_number }}" \
            --body "Closes #${{ steps.extract.outputs.issue_number }}\n\nImplemented by Claude bot" \
            --base main \
            --head ${{ steps.extract.outputs.branch_name }}
