name: Label Updater

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  update-label:
    if: contains(github.event.comment.body, 'LABEL_UPDATE:')
    runs-on: ubuntu-latest
    steps:
      - name: Update Label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # コメントから新しいラベルを抽出
          COMMENT="${{ github.event.comment.body }}"
          NEW_LABEL=$(echo "$COMMENT" | grep -oP 'LABEL_UPDATE:\K\S+' || exit 0)
          
          if [ -z "$NEW_LABEL" ]; then
            echo "No label found"
            exit 0
          fi
          
          ISSUE=${{ github.event.issue.number }}
          
          # 古いworkflow:ラベルを削除して新しいラベルを追加
          gh issue edit $ISSUE -R ${{ github.repository }} \
            --remove-label "workflow:ready-for-analysis" \
            --remove-label "workflow:ready-for-impl" \
            --remove-label "workflow:ready-for-review" \
            --add-label "$NEW_LABEL"
          
          # 確認コメント
          gh issue comment $ISSUE -R ${{ github.repository }} \
            --body "✅ ラベルを \`$NEW_LABEL\` に更新しました。"
