name: Claude Label Updater

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  update-label:
    # claude[bot]のコメントのみ処理
    if: |
      github.event.comment.user.login == 'claude[bot]' &&
      contains(github.event.comment.body, 'LABEL_UPDATE:')
    runs-on: ubuntu-latest
    steps:
      - name: Update Label
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body;
            
            // LABEL_UPDATE:の後の文字列を取得
            const match = comment.match(/LABEL_UPDATE:([^\s\n]+)/);
            if (!match) {
              console.log('No valid LABEL_UPDATE found');
              return;
            }
            
            const newLabel = match[1];
            const issue = context.issue.number;
            
            console.log(`Updating issue #${issue} with label: ${newLabel}`);
            
            // workflow:で始まる既存のラベルを削除
            const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({
              ...context.repo,
              issue_number: issue
            });
            
            for (const label of currentLabels) {
              if (label.name.startsWith('workflow:')) {
                console.log(`Removing: ${label.name}`);
                await github.rest.issues.removeLabel({
                  ...context.repo,
                  issue_number: issue,
                  name: label.name
                });
              }
            }
            
            // 新しいラベルを追加
            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number: issue,
              labels: [newLabel]
            });
            
            // 確認コメント
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: issue,
              body: `✅ ラベルを \`${newLabel}\` に更新しました。`
            });
