name: Label Updater

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  update-label:
    if: contains(github.event.comment.body, 'LABEL_UPDATE:')
    runs-on: ubuntu-latest
    steps:
      - name: Update Label
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body;
            const match = comment.match(/LABEL_UPDATE:(\S+)/);
            
            if (!match) {
              console.log('No label found');
              return;
            }
            
            const newLabel = match[1];
            const issue = context.issue.number;
            
            console.log(`Updating issue #${issue} with label: ${newLabel}`);
            
            // Remove old labels
            try {
              await github.rest.issues.removeLabel({
                ...context.repo,
                issue_number: issue,
                name: 'workflow:ready-for-analysis'
              });
            } catch (e) {}
            
            try {
              await github.rest.issues.removeLabel({
                ...context.repo,
                issue_number: issue,
                name: 'workflow:ready-for-impl'
              });
            } catch (e) {}
            
            try {
              await github.rest.issues.removeLabel({
                ...context.repo,
                issue_number: issue,
                name: 'workflow:ready-for-review'
              });
            } catch (e) {}
            
            // Add new label
            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number: issue,
              labels: [newLabel]
            });
            
            // Post comment
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: issue,
              body: `✅ ラベルを \`${newLabel}\` に更新しました。`
            });
