cat > .github/workflows/claude-label-updater.yml << 'EOF'
name: Claude Label Updater

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  update-label-from-comment:
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, 'LABEL_UPDATE:')
    runs-on: ubuntu-latest
    steps:
      - name: Update label
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment;
            console.log(`Processing comment from: ${comment.user.login}`);
            
            // LABEL_UPDATE:を探す
            const match = comment.body.match(/LABEL_UPDATE:([^\s]+)/);
            if (!match) {
              console.log('No LABEL_UPDATE found');
              return;
            }
            
            const newLabel = match[1];
            console.log(`Updating label to: ${newLabel}`);
            
            try {
              // 現在のラベルを取得
              const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number
              });
              
              // workflow:で始まるラベルを削除
              for (const label of currentLabels) {
                if (label.name.startsWith('workflow:')) {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    name: label.name
                  });
                }
              }
              
              // 新しいラベルを追加
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [newLabel]
              });
              
              // 確認コメント
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `✅ ラベルを \`${newLabel}\` に更新しました。`
              });
              
            } catch (error) {
              console.error('Error:', error);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `❌ エラー: ${error.message}`
              });
            }
EOF

git add .github/workflows/claude-label-updater.yml
git commit -m "Remove user restriction for label updates"
git push
