name: Add Label GH

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  add-label:
    if: contains(github.event.comment.body, 'LABEL_UPDATE:workflow:ready-for-impl')
    runs-on: ubuntu-latest
    steps:
      - name: Add Label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit ${{ github.event.issue.number }} \
            -R ${{ github.repository }} \
            --add-label "workflow:ready-for-impl"
          
          gh issue comment ${{ github.event.issue.number }} \
            -R ${{ github.repository }} \
            --body "✅ ラベル \`workflow:ready-for-impl\` を追加しました。"
