name: Simple Label Update

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  update-label:
    # claude[bot]のコメントでLABEL_UPDATE:を含む場合のみ
    if: |
      github.event.comment.user.login == 'claude[bot]' &&
      contains(github.event.comment.body, 'LABEL_UPDATE:')
    runs-on: ubuntu-latest
    steps:
      - name: Add Label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 3秒待機（claude.ymlとの競合回避）
          sleep 3
          
          # コメントからラベルを抽出
          COMMENT='${{ github.event.comment.body }}'
          LABEL=$(echo "$COMMENT" | grep -o 'LABEL_UPDATE:[^ ]*' | cut -d: -f2)
          
          if [ -n "$LABEL" ]; then
            echo "Adding label: $LABEL"
            
            # ラベルを追加
            gh issue edit ${{ github.event.issue.number }} \
              -R ${{ github.repository }} \
              --add-label "$LABEL"
          fi
